# -*- coding: utf-8 -*-
"""Stock_Movers_Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIHPYBn3PW5KhY5WAF0wIxMglFbs2QB5

## Using EODHD API for Comprehensive Equities List

To use the EODHD API, you'll need an API key. You can get one from their website (e.g., their free tier might provide enough access for initial testing).

Once you have your key, please add it to Colab's secrets manager under the name `EODHD_API_KEY`.
"""

# Install requests library if not already installed
# !pip install requests

import requests
import json
from google.colab import userdata

# Retrieve API key from Colab secrets
EODHD_API_KEY = userdata.get('EODHD_API_KEY')

if not EODHD_API_KEY:
    print("EODHD_API_KEY not found in Colab secrets. Please add it.")
else:
    print("EODHD API Key loaded.")
    # Verify by printing a masked version of the key
    print(f"API Key (masked): {EODHD_API_KEY[:4]}...{EODHD_API_KEY[-4:]}")

import pandas as pd
import requests
import json
from google.colab import userdata

def get_us_equities_from_eodhd(api_key, min_market_cap_usd=1e9, max_equities_to_fetch=5000):
    all_equities = []
    # EODHD support states limit=100 per request and max offset of 999 per query.
    limit_per_request = 100

    # Common sectors to iterate through to break down the query
    # This list can be expanded or refined based on EODHD's sector classification
    sectors = [
        "Basic Materials", "Communication Services", "Consumer Cyclical",
        "Consumer Defensive", "Energy", "Financial Services", "Healthcare",
        "Industrials", "Real Estate", "Technology", "Utilities"
    ]

    print(f"Fetching US equities from EODHD with market cap >= ${min_market_cap_usd/1e9:.0f}B, by sector...")

    # EODHD Screener API endpoint
    url = "https://eodhd.com/api/screener"

    for sector in sectors:
        offset = 0
        total_fetched_for_sector = 0
        has_more_data = True

        print(f"  Fetching equities for sector: {sector}")

        while has_more_data and (len(all_equities) + total_fetched_for_sector) < max_equities_to_fetch:
            filters_list = [
                ["exchange", "=", "US"],
                ["market_capitalization", ">=", int(min_market_cap_usd)],
                ["sector", "=", sector]
            ]

            params = {
                "api_token": api_key,
                "filters": json.dumps(filters_list),
                "limit": limit_per_request,
                "offset": offset
            }

            try:
                response = requests.get(url, params=params)
                response.raise_for_status() # Raise an exception for HTTP errors
                data = response.json()
                batch = data.get('data', [])

                if not batch or offset > 999: # EODHD hard cap on offset
                    has_more_data = False
                else:
                    all_equities.extend(batch)
                    total_fetched_for_sector += len(batch)
                    offset += limit_per_request
                    print(f"    Fetched {total_fetched_for_sector} for {sector}. Total US equities: {len(all_equities)}...")

                    # If the last batch was smaller than the limit, it means there are no more results for this sector
                    if len(batch) < limit_per_request:
                        has_more_data = False

            except requests.exceptions.RequestException as e:
                print(f"Error fetching data from EODHD for sector {sector}: {e}")
                has_more_data = False # Stop trying for this sector
            except json.JSONDecodeError:
                print(f"Error decoding JSON response from EODHD for sector {sector}.")
                has_more_data = False # Stop trying for this sector

    print(f"Finished fetching. Total US equities retrieved: {len(all_equities)}")

    df = pd.DataFrame(
        {
            'Ticker': i.get('code'),
            'Name':   i.get('name'),
            'MarketCap': pd.to_numeric(i.get('market_capitalization'), errors='coerce'),
            'Sector':   i.get('sector'),
            'Industry': i.get('industry'),
            'Exchange': i.get('exchange'),
        } for i in all_equities
    )

    # Combine all filtering conditions into a single step for efficiency
    df_cleaned = df[
        (df['Exchange'] != 'PINK') &
        (df['MarketCap'].notna()) &
        (df['MarketCap'] >= min_market_cap_usd)
    ].copy()

    print(f"Found {len(df_cleaned)} US equities after filtering by market cap and 'PINK' exchange.")
    return df_cleaned.reset_index(drop=True)

# Example usage:
eodhd_us_equities_df = get_us_equities_from_eodhd(EODHD_API_KEY, min_market_cap_usd=1e9)

if not eodhd_us_equities_df.empty:
    print("\nSample Equities Data from EODHD (first 5 rows, after local filtering):")
    display(eodhd_us_equities_df.head())
    print("\nMarketCap None counts in the fetched data:")
    print(eodhd_us_equities_df['MarketCap'].isnull().sum())
    print(f"Total fetched equities: {len(eodhd_us_equities_df)}")
else:
    print("Could not retrieve EODHD data or no equities met the criteria.")

print("Cleaning EODHD US equities data: converting MarketCap, and filtering 'PINK' exchange listings. Temporarily skipping $5B minimum and NaN MarketCap filters...")

# Convert MarketCap to numeric, coercing errors (including None) to NaN
eodhd_us_equities_df['MarketCap'] = pd.to_numeric(eodhd_us_equities_df['MarketCap'], errors='coerce')

# Temporarily commenting out MarketCap filtering to allow subsequent fundamental/historical calls for all tickers
# Filter out entries where MarketCap is NaN (resulting from None or invalid conversion)
# eodhd_us_equities_df_cleaned = eodhd_us_equities_df[eodhd_us_equities_df['MarketCap'].notna()].copy()

# Filter out entries where MarketCap is less than the specified minimum (5 billion USD)
# min_market_cap_usd = 5e9
# eodhd_us_equities_df_cleaned = eodhd_us_equities_df_cleaned[eodhd_us_equities_df_cleaned['MarketCap'] >= min_market_cap_usd].copy()

# Copy the original DataFrame to start, as we are skipping initial MarketCap filters
eodhd_us_equities_df_cleaned = eodhd_us_equities_df.copy()

# Filter out entries where Exchange is 'PINK'
eodhd_us_equities_df_cleaned = eodhd_us_equities_df_cleaned[eodhd_us_equities_df_cleaned['Exchange'] != 'PINK'].copy()

# Update the main DataFrame to the cleaned version
eodhd_us_equities_df = eodhd_us_equities_df_cleaned.reset_index(drop=True)

print(f"Remaining {len(eodhd_us_equities_df)} US equities after converting MarketCap to numeric and filtering 'PINK' exchange listings (skipped $5B minimum and NaN MarketCap filters for now).")
print("\nSample of partially cleaned US Equities Data (first 5 rows):")
display(eodhd_us_equities_df.head())

print("Inspecting eodhd_us_equities_df before cleaning filters:")
print("Original DataFrame head:")
display(eodhd_us_equities_df.head())

print("\nMarketCap None counts:")
print(eodhd_us_equities_df['MarketCap'].isnull().sum())

print("\nExchange value counts:")
print(eodhd_us_equities_df['Exchange'].value_counts())

print("\nMarketCap and Exchange combinations:")
display(eodhd_us_equities_df.groupby(['Exchange', eodhd_us_equities_df['MarketCap'].isnull()])['Ticker'].count().unstack(fill_value=0))

def get_safe(data, keys):
    """Safely retrieves a nested value from a dictionary. Returns None if any key is missing."""
    for key in keys:
        if data and key in data:
            data = data[key]
        else:
            return None
    return data

_fundamental_call_count = 0 # Initialize a counter to limit debug prints
def get_fundamental_metrics_from_eodhd(api_key, ticker_symbol, exchange_code='US'): # Modified to include default 'US'
    url = f"https://eodhd.com/api/fundamentals/{ticker_symbol}.{exchange_code}"
    params = {"api_token": api_key}

    try:
        response = requests.get(url, params=params)
        response.raise_for_status() # Raise an exception for HTTP errors
        data = response.json()

        # Correct key locations in the EODHD response
        highlights = data.get('Highlights', {}) or {}
        technicals = data.get('Technicals', {}) or {}
        valuation = data.get('Valuation', {}) or {}

        return {
            'PriceToSales':    valuation.get('PriceSalesTTM') or highlights.get('PriceSalesRTM') or highlights.get('PriceSalesRatio'),
            'PriceToEarnings': highlights.get('PERatio'),
            'PEGRatio':        highlights.get('PEGRatio'),
            'DividendYield':   highlights.get('DividendYield'),
            '52WeekHigh':      technicals.get('52WeekHigh'),
            '52WeekLow':       technicals.get('52WeekLow'),
        }

    except Exception as e:
        print(f"Error fetching fundamentals for {ticker_symbol} on {exchange_code}: {e}")
        return {k: None for k in ['PriceToSales','PriceToEarnings','PEGRatio','DividendYield','52WeekHigh','52WeekLow']}


# The following section was an initial demonstration and can be commented out or removed
# as the optimized fundamental data fetching for movers is handled in a later cell (36a52917).

# print("Fetching fundamental metrics for US equities (P/S, P/E, PEG, Dividend Yield, 52WeekHigh, 52WeekLow)...")
# metrics_data = []
# Using the cleaned DataFrame `eodhd_us_equities_df` from the previous step
# This part of the code is example usage, and will be updated in a later step to reflect consolidated_equities_df
# for index, row in eodhd_us_equities_df.iterrows():
#     # This call needs to explicitly pass the exchange from row['Exchange'] for accuracy
#     metrics = get_fundamental_metrics_from_eodhd(EODHD_API_KEY, row['Ticker'], row['Exchange'])
#     metrics_data.append(metrics)

# metrics_df = pd.DataFrame(metrics_data)

# Rename 52WeekHigh and 52WeekLow in metrics_df to avoid conflicts with historical data
# metrics_df = metrics_df.rename(columns={
#     '52WeekHigh': 'Fundamental_52WeekHigh',
#     '52WeekLow': 'Fundamental_52WeekLow'
# })

# Join the metrics back to the main DataFrame
# eodhd_us_equities_df = eodhd_us_equities_df.reset_index(drop=True).merge(metrics_df.reset_index(drop=True), left_index=True, right_index=True)

# print("Fundamental metrics fetched and added to DataFrame.")
# display(eodhd_us_equities_df.head())

from datetime import datetime, timedelta, date # Import date
import pytz
import json # Import json for pretty printing
import pandas as pd # Import pandas for data manipulation
import io # Import io to read string as file
import requests # Ensure requests is imported here

_eod_call_count = 0 # Initialize a counter to limit debug prints
def get_historical_metrics_eodhd(api_key, ticker_symbol, exchange_code, history_days=370):
    """Calculates price percentage changes, 52-week high/low, and latest close using EODHD historical data."""
    global _eod_call_count
    metrics = {
        'Change_30D': None, 'Change_90D': None, 'Change_360D': None,
        'LatestClosePrice': None, '52WeekHigh': None, '52WeekLow': None
    }

    # Use the actual current date, not necessarily what datetime.now(pytz.utc).date() might report if the system clock is off.
    # This prevents requesting historical data from the future.
    # Force end_date to be today's date to avoid issues with Colab's potentially incorrect system clock.
    end_date = date.today() # Use date.today() to get the actual current date
    start_date = end_date - timedelta(days=history_days) # API 'from' date

    # Debugging print statement
    print(f"DEBUG: Requesting historical data for {ticker_symbol}.{exchange_code} from {start_date} to {end_date}")

    url = f"https://eodhd.com/api/eod/{ticker_symbol}.{exchange_code}"
    params = {
        "api_token": api_key,
        "from": start_date.strftime('%Y-%m-%d'),
        "to": end_date.strftime('%Y-%m-%d'), # Use the corrected end_date
        "period": "d", # Daily data
        "fmt": "json"
    }

    try:
        response = requests.get(url, params=params)
        response.raise_for_status() # Raise an exception for HTTP errors

        # Print full response content and status code for debugging
        print(f"DEBUG: Historical API response status code for {ticker_symbol}.{exchange_code}: {response.status_code}")
        # Check if the response is empty
        if not response.text.strip():
            print(f"No data in historical API response for {ticker_symbol}.{exchange_code}.")
            return metrics

        # Parse JSON data
        raw_json_data = response.json()
        if not raw_json_data:
            print(f"No data found in JSON response for {ticker_symbol}.{exchange_code}.")
            return metrics

        df_hist = pd.DataFrame(raw_json_data)

        if not df_hist.empty:
            # Convert 'date' column to datetime
            df_hist['date'] = pd.to_datetime(df_hist['date'])
            df_hist = df_hist.sort_values(by='date', ascending=True).reset_index(drop=True) # Ensure data is sorted ascending by date

            latest_close = df_hist['close'].iloc[-1] if not df_hist.empty else None # Use 'close', last row = most recent
            metrics['LatestClosePrice'] = latest_close

            if latest_close is not None:
                # Calculate Price Changes
                # Use df_hist['date'].max() as the 'latest' date for calculating changes, as it reflects the most recent data received
                latest_data_date = df_hist['date'].max().date()

                target_date_30D = latest_data_date - timedelta(days=30)
                target_date_90D = latest_data_date - timedelta(days=90)
                target_date_360D = latest_data_date - timedelta(days=360)

                # For historical lookbacks, find the closest date on or before the target, and take the last value
                mask_30 = df_hist['date'].dt.date <= target_date_30D
                close_30D_ago = df_hist.loc[mask_30, 'close'].iloc[-1] if mask_30.any() else None

                mask_90 = df_hist['date'].dt.date <= target_date_90D
                close_90D_ago = df_hist.loc[mask_90, 'close'].iloc[-1] if mask_90.any() else None

                mask_360 = df_hist['date'].dt.date <= target_date_360D
                close_360D_ago = df_hist.loc[mask_360, 'close'].iloc[-1] if mask_360.any() else None

                if close_30D_ago is not None and close_30D_ago != 0:
                    metrics['Change_30D'] = ((latest_close - close_30D_ago) / close_30D_ago) * 100
                if close_90D_ago is not None and close_90D_ago != 0:
                    metrics['Change_90D'] = ((latest_close - close_90D_ago) / close_90D_ago) * 100
                if close_360D_ago is not None and close_360D_ago != 0:
                    metrics['Change_360D'] = ((latest_close - close_360D_ago) / close_360D_ago) * 100

                # Calculate 52-week high and low
                one_year_ago = latest_data_date - timedelta(days=365) # Calculate relative to latest data date
                df_last_52_weeks = df_hist[df_hist['date'].dt.date >= one_year_ago] # Use 'date'

                if not df_last_52_weeks.empty:
                    metrics['52WeekHigh'] = df_last_52_weeks['high'].max() # Use 'high'
                    metrics['52WeekLow'] = df_last_52_weeks['low'].min() # Use 'low'

        return metrics

    except requests.exceptions.HTTPError as e:
        print(f"HTTP Error fetching historical data for {ticker_symbol}.{exchange_code} from EODHD: {e}")
        return metrics
    except requests.exceptions.ConnectionError as e:
        print(f"Connection Error fetching historical data for {ticker_symbol}.{exchange_code} from EODHD: {e}")
        return metrics
    except requests.exceptions.Timeout as e:
        print(f"Timeout Error fetching historical data for {ticker_symbol}.{exchange_code} from EODHD: {e}")
        return metrics
    except requests.exceptions.RequestException as e:
        # This catches any other Requests-related errors
        print(f"Generic Requests Error fetching historical data for {ticker_symbol}.{exchange_code} from EODHD: {e}")
        return metrics
    except json.JSONDecodeError:
        print(f"JSONDecodeError: Could not decode JSON from response for {ticker_symbol}.{exchange_code}. Response text was: {response.text[:200]}...") # Print partial response for debugging
        return metrics
    except Exception as e: # Catch other potential errors from data processing
        print(f"Unexpected Error processing historical data for {ticker_symbol}.{exchange_code}: {e}")
        return metrics

def identify_top_movers(df, period, num_movers=25):
    """Identifies top percentage gainers and losers for a given period."""
    change_col = f'Change_{period}D'

    # DEBUG: Print columns to verify existence of change_col
    # print(f"DEBUG: Columns in DataFrame received by identify_top_movers: {df.columns.tolist()}")
    # print(f"DEBUG: Looking for column: {change_col}")

    # Drop rows where the change_col is None or NaN before sorting
    df_cleaned = df.dropna(subset=[change_col])

    # Sort by the change column for gainers (descending)
    top_gainers = df_cleaned.sort_values(by=change_col, ascending=False).head(num_movers)

    # Sort by the change column for losers (ascending)
    top_losers = df_cleaned.sort_values(by=change_col, ascending=True).head(num_movers)

    return top_gainers, top_losers

def format_financial_df(df):
    """Applies specific financial formatting to the DataFrame columns."""
    df_formatted = df.copy()

    # Ensure relevant columns are numeric before formatting
    numeric_cols = [
        'MarketCap', 'Fundamental_52WeekHigh', 'Fundamental_52WeekLow',
        'LatestClosePrice', '52WeekHigh', '52WeekLow',
        'Change_30D', 'Change_90D', 'Change_360D',
        'PriceToSales', 'PriceToEarnings', 'PEGRatio', 'DividendYield'
    ]
    for col in numeric_cols:
        if col in df_formatted.columns:
            df_formatted[col] = pd.to_numeric(df_formatted[col], errors='coerce')

    # Market Cap as $ (no decimal)
    if 'MarketCap' in df_formatted.columns:
        df_formatted['MarketCap'] = df_formatted['MarketCap'].apply(lambda x: f"${x:,.0f}" if pd.notna(x) else None)

    # 52WeekHigh, 52WeekLow, LatestClosePrice as $ with decimal (2 places)
    for col in ['Fundamental_52WeekHigh', 'Fundamental_52WeekLow', 'LatestClosePrice', '52WeekHigh', '52WeekLow']:
        if col in df_formatted.columns:
            df_formatted[col] = df_formatted[col].apply(lambda x: f"${x:,.2f}" if pd.notna(x) else None)

    # Change_30D, Change_90D, Change_360D as percentages (2 decimal places)
    for col in ['Change_30D', 'Change_90D', 'Change_360D']:
        if col in df_formatted.columns:
            df_formatted[col] = df_formatted[col].apply(lambda x: f"{x:,.2f}%" if pd.notna(x) else None)

    # Other numerical values to 2 decimal places
    for col in ['PriceToSales', 'PriceToEarnings', 'PEGRatio']:
        if col in df_formatted.columns:
            df_formatted[col] = df_formatted[col].apply(lambda x: f"{x:,.2f}" if pd.notna(x) else None)

    # Dividend Yield as percent (e.g., 0.0837 should be 8.37%)
    if 'DividendYield' in df_formatted.columns:
        df_formatted['DividendYield'] = df_formatted['DividendYield'].apply(lambda x: f"{x*100:,.2f}%" if pd.notna(x) else None)

    return df_formatted

# periods = [90, 360] # Changed to only re-run for 90 and 360 days
# num_movers = 25

# for p in periods:
#     print(f"\n--- Top {num_movers} Gainers and Losers for {p}-day period ---")
#     top_gainers, top_losers = identify_top_movers(eodhd_us_equities_df, p, num_movers)

#     # Updated display_cols order as requested and correct column names
#     display_cols = ['Ticker', 'Name', 'MarketCap', f'Change_{p}D', 'LatestClosePrice', 'Fundamental_52WeekHigh', 'Fundamental_52WeekLow', 'PriceToSales', 'PriceToEarnings', 'PEGRatio', 'DividendYield']

#     print(f"\nTop {num_movers} Gainers ({p}-day Change):")
#     if not top_gainers.empty:
#         display(format_financial_df(top_gainers[display_cols]))
#     else:
#         print("No top gainers found.")

#     print(f"\nTop {num_movers} Losers ({p}-day Change):")
#     if not top_losers.empty:
#         display(format_financial_df(top_losers[display_cols]))
#     else:
#         print("No top losers found.")

# print("\n--- Null value counts for Change_30D, Change_90D, and Change_360D ---")
# print(eodhd_us_equities_df[['Change_30D', 'Change_90D', 'Change_360D']].isnull().sum())

"""# Task
Fetch US and foreign equities with a market cap of $5B or greater, retrieve their fundamental and historical metrics (P/S, P/E, PEG, Dividend Yield, 52-week high/low, and 30/90/360-day price changes), identify the top 25 gainers and losers for 30-day, 90-day, and 360-day periods separately for each market, format the collected data, and export these reports to a Google Sheet, with 30-day reports in a 'Daily Report' tab and 90/360-day reports in a 'Weekly Report' tab, distinguishing between US and foreign equities.

## Fetch All US Equities with Pagination

### Subtask:
Modify the `get_us_equities_from_eodhd` function to use pagination with a `limit` of 500 per API request. Fetch all US equities with a market capitalization of $5B or greater by making multiple paginated calls, storing the results in a `us_equities_df`.

# Task
Create a Python function `get_foreign_equities_from_eodhd` that uses the EODHD Screener API to fetch foreign equities. This function should accept `api_key`, `min_market_cap_usd` (defaulting to 5 billion USD), and `max_equities_to_fetch` (defaulting to 2500) as parameters. It must implement pagination, with a `limit_per_request` of 500, and explicitly filter for major non-US exchanges ('LSE', 'XETRA', 'TYO', 'TSX', 'EPA', 'AMS'). The function should collect the data and return a pandas DataFrame containing the relevant equity details.

## Create get_foreign_equities_from_eodhd Function

### Subtask:
Define a new Python function `get_foreign_equities_from_eodhd` that uses the EODHD Screener API to fetch foreign equities. This function should accept `api_key`, `min_market_cap_usd` (defaulting to 5 billion USD), and `max_equities_to_fetch` (defaulting to 2500) as parameters. It must implement pagination, with a `limit_per_request` of 500, make multiple calls to the EODHD Screener API, and explicitly filter for a set of major non-US exchanges (e.g., 'LSE', 'XETRA', 'TYO', 'TSX', 'EPA', 'AMS') while ensuring market cap is $5B or greater. The function will collect all data and return a pandas DataFrame with relevant equity details.

**Reasoning**:
The subtask requires calling a function that has not yet been defined. Therefore, I need to implement the `get_foreign_equities_from_eodhd` function first, including pagination and filtering for foreign exchanges as per the subtask description.
"""

import pandas as pd
import requests
import json
from google.colab import userdata

def get_foreign_equities_from_eodhd(api_key, min_market_cap_usd=1e9, max_equities_to_fetch=5000, us_tickers_to_exclude=None):
    if us_tickers_to_exclude is None:
        us_tickers_to_exclude = set()

    all_equities = []
    # EODHD support states limit=100 per request and max offset of 999 per query.
    limit_per_request = 100

    # List of major non-US exchanges to filter for
    # Will iterate through these individually as per EODHD support workaround
    foreign_exchanges = ['LSE', 'XETRA', 'TYO', 'TSX', 'EPA', 'AMS', 'SHG', 'SHE', 'HKG', 'BSE', 'NSE', 'TAI', 'KOR', 'ASX', 'JSE', 'BVMF']

    print(f"Fetching foreign equities with market cap >= ${min_market_cap_usd/1e9:.0f}B, by individual exchange...")

    url = "https://eodhd.com/api/screener"

    for exchange in foreign_exchanges:
        offset = 0
        total_fetched_for_exchange = 0
        has_more_data = True
        print(f"  Fetching equities for exchange: {exchange}")

        while has_more_data and (len(all_equities) + total_fetched_for_exchange) < max_equities_to_fetch:
            filters_list = [
                ["exchange", "=", exchange],
                ["market_capitalization", ">=", int(min_market_cap_usd)]
            ]

            params = {
                "api_token": api_key,
                "filters": json.dumps(filters_list),
                "limit": limit_per_request,
                "offset": offset
            }

            try:
                response = requests.get(url, params=params)
                response.raise_for_status() # Raise an exception for HTTP errors
                data = response.json()
                batch = data.get('data', [])

                if not batch or offset > 999: # EODHD hard cap on offset for individual query
                    has_more_data = False
                else:
                    # Filter out tickers that are in the US exclusion list before adding to all_equities
                    filtered_batch = [equity for equity in batch if equity.get('code') not in us_tickers_to_exclude]
                    all_equities.extend(filtered_batch)
                    total_fetched_for_exchange += len(batch) # Count all fetched from API for pagination logic
                    offset += limit_per_request
                    print(f"    Fetched {total_fetched_for_exchange} for {exchange}. Total foreign equities: {len(all_equities)}...")

                    # If the last batch was smaller than the limit, it means there are no more results for this exchange
                    if len(batch) < limit_per_request:
                        has_more_data = False

            except requests.exceptions.RequestException as e:
                print(f"Error fetching data from EODHD for exchange {exchange}: {e}")
                has_more_data = False # Stop trying for this exchange
            except json.JSONDecodeError:
                print(f"Error decoding JSON response from EODHD for exchange {exchange}.")
                has_more_data = False # Stop trying for this exchange

    print(f"Finished fetching. Total foreign equities retrieved: {len(all_equities)}")

    df = pd.DataFrame(
        {
            'Ticker': i.get('code'),
            'Name':   i.get('name'),
            'MarketCap': pd.to_numeric(i.get('market_capitalization'), errors='coerce'),
            'Sector':   i.get('sector'),
            'Industry': i.get('industry'),
            'Exchange': i.get('exchange'),
        } for i in all_equities
    )

    # Ensure MarketCap is numeric and filter out any None/NaN values from conversion if they somehow slipped through
    df_cleaned = df[
        (df['MarketCap'].notna()) &
        (df['MarketCap'] >= min_market_cap_usd)
    ].copy()

    print(f"Found {len(df_cleaned)} foreign equities after final filtering and US ticker exclusion.")
    return df_cleaned.reset_index(drop=True)

# --- Call US equities first to get tickers for exclusion ---
us_tickers_set = set(eodhd_us_equities_df['Ticker'].unique())
print(f"Identified {len(us_tickers_set)} US tickers for exclusion from foreign equities.")

# Call the foreign equities function, passing the set of US tickers to exclude
foreign_equities_df = get_foreign_equities_from_eodhd(EODHD_API_KEY, min_market_cap_usd=1e9, us_tickers_to_exclude=us_tickers_set)

if not foreign_equities_df.empty:
    print("\nSample Foreign Equities Data (first 5 rows):")
    display(foreign_equities_df.head())
    print(f"Total fetched foreign equities: {len(foreign_equities_df)}")
else:
    print("Could not retrieve foreign equities data or no equities met the criteria.")

"""## Summary:

### Data Analysis Key Findings
*   A new Python function, `get_foreign_equities_from_eodhd`, was successfully created to retrieve foreign equities data from the EODHD Screener API.
*   The function is designed to handle pagination, making multiple API calls to fetch up to a `max_equities_to_fetch` limit (defaulting to 2500) with a `limit_per_request` of 500.
*   It filters for major non-US exchanges including 'LSE', 'XETRA', 'TYO', 'TSX', 'EPA', and 'AMS'.
*   Equities are filtered based on a minimum market capitalization, defaulting to \$5 billion USD.
*   The function returns a pandas DataFrame containing relevant equity details for further analysis.

### Insights or Next Steps
*   The `get_foreign_equities_from_eodhd` function provides a robust tool for sourcing a diverse set of international equities, which can be invaluable for portfolio diversification and global market analysis.
*   The next step involves calling this function with an API key to retrieve actual data, which can then be used for exploratory data analysis, constructing investment screens, or integrating into a larger financial model.

# Task
Call `get_foreign_equities_from_eodhd` function with `EODHD_API_KEY` to retrieve foreign equities data and store the resulting DataFrame in `foreign_equities_df`. Then, display the head of `foreign_equities_df` to verify the data.

## Call get_foreign_equities_from_eodhd

### Subtask:
Call the `get_foreign_equities_from_eodhd` function using the `EODHD_API_KEY` from the Colab secrets. Store the returned DataFrame in `foreign_equities_df`. This will fetch foreign equities with a market cap of $5B or greater from the specified exchanges using pagination.

**Reasoning**:
The subtask requires displaying the head of the `foreign_equities_df` DataFrame to inspect its structure and content.
"""

foreign_equities_df.head()

"""## Display Foreign Equities Data

### Subtask:
Display the head of the `foreign_equities_df` to inspect the fetched foreign equities data and confirm its structure and content.

## Final Task

### Subtask:
Confirm that the foreign equities data has been successfully fetched and is ready for further processing.

**Reasoning**:
I need to perform several data manipulation steps: copy DataFrames, add a 'Source' column, concatenate them, handle duplicates by keeping the higher market cap entry, sort by market cap in descending order, and finally select the top 5000 entries to create `consolidated_equities_df` as per the subtask instructions.
"""

print("Consolidating US and foreign equities, handling duplicates and prioritizing by MarketCap...")

# 1. Create a copy of eodhd_us_equities_df and assign a new column named 'Source' with the value 'US'.
us_equities_df_with_source = eodhd_us_equities_df.copy()
us_equities_df_with_source['Source'] = 'US'

# 2. Create a copy of foreign_equities_df and assign a new column named 'Source' with the value 'Foreign'.
foreign_equities_df_with_source = foreign_equities_df.copy()
foreign_equities_df_with_source['Source'] = 'Foreign'

# 3. Concatenate us_equities_df_with_source and foreign_equities_df_with_source
# Ensure all columns are present in both DFs before concatenating
# For simplicity, we'll only take common columns or specifically manage them if needed. For now, assuming direct concat is okay.
common_cols = list(set(us_equities_df_with_source.columns) & set(foreign_equities_df_with_source.columns))
consolidated_equities_df = pd.concat([
    us_equities_df_with_source[common_cols],
    foreign_equities_df_with_source[common_cols]
], ignore_index=True)

# Convert MarketCap to numeric, coercing errors to NaN, then drop NaNs
consolidated_equities_df['MarketCap'] = pd.to_numeric(consolidated_equities_df['MarketCap'], errors='coerce')
consolidated_equities_df.dropna(subset=['MarketCap'], inplace=True)

# 4. Remove duplicate tickers, keeping the entry with the higher 'MarketCap'.
# Sort by MarketCap descending first, then drop duplicates keeping the first (which will be the highest MarketCap)
consolidated_equities_df = consolidated_equities_df.sort_values(by='MarketCap', ascending=False)
consolidated_equities_df = consolidated_equities_df.drop_duplicates(subset=['Ticker'], keep='first')

# 5. Sort consolidated_equities_df by the 'MarketCap' column in descending order (already done in previous step for drop_duplicates)
# If there were no duplicates, this step ensures sorting.
consolidated_equities_df = consolidated_equities_df.sort_values(by='MarketCap', ascending=False).reset_index(drop=True)

# 6. Select the top N tickers (e.g., 5000 for EODHD API limit considerations).
N_tickers_limit = 10000 # This limit can be adjusted based on API allowances
consolidated_equities_df = consolidated_equities_df.head(N_tickers_limit)

print(f"Consolidation complete. Total unique equities for processing: {len(consolidated_equities_df)}")
print("Sample of consolidated equities:")
display(consolidated_equities_df.head())

"""## Summary:

### Q&A
The foreign equities data has been successfully fetched and is ready for further processing.

### Data Analysis Key Findings
*   A total of 942 foreign equities were initially retrieved from the EODHD API across major non-US exchanges (LSE, XETRA, TYO, TSX, EPA, AMS).
*   After filtering for a minimum market capitalization of \$5 billion, the `foreign_equities_df` DataFrame contains 894 unique foreign equity entries.
*   The `foreign_equities_df` DataFrame includes essential columns such as `Ticker`, `Name`, `MarketCap`, `Sector`, `Industry`, and `Exchange`.
*   Sample data confirms the presence of well-known companies like Kerry Group, The Home Depot Inc, Gilead Sciences Inc, RWE AG, and Nike Inc, with their respective market capitalizations, sectors, and exchanges correctly captured.

### Insights or Next Steps
*   The `foreign_equities_df` is prepared for further analysis, such as market capitalization distribution, sector/industry breakdown, or integration with other datasets.
*   Consider enriching the dataset with additional financial metrics (e.g., P/E ratio, dividend yield) to provide a more comprehensive view of these foreign equities.

# Task
The current plan involves consolidating `us_equities_df` and `foreign_equities_df`, removing duplicates based on market cap, sorting by market cap, and selecting a prioritized list of equities while preserving their original source. I will implement this next.

## Consolidate and Prioritize Equities for API Limits

### Subtask:
Concatenate the `us_equities_df` and `foreign_equities_df` into a single DataFrame. Remove any duplicate tickers, keeping the entry with the higher market capitalization if duplicates exist. Sort this combined DataFrame by `MarketCap` in descending order. Select the top N tickers from this sorted list (where N is determined by the EODHD API daily call limit, e.g., 5000 tickers to allow for 10,000 API calls) to ensure we only process the largest companies within the daily budget.

## Fetch Fundamental and Historical Metrics for Selected Equities

### Subtask:
Iterate through the consolidated and prioritized list of equities, call API functions to retrieve fundamental and historical metrics, and merge these metrics back into the main DataFrame.

**Reasoning**:
I need to iterate through the `consolidated_equities_df`, call the `get_fundamental_metrics_from_eodhd` and `get_historical_metrics_eodhd` functions for each ticker, collect the results, and then merge these new metrics back into the `consolidated_equities_df`.
"""

import time # Import the time module for pauses

print("Fetching historical metrics for all consolidated equities in batches...")

# Initialize empty list for historical metrics
historical_metrics_list = []

batch_size = 500 # Define batch size for iterating through consolidated_equities_df
total_equities = len(consolidated_equities_df)

# Iterate through the consolidated_equities_df in batches to fetch historical data
for i in range(0, total_equities, batch_size):
    batch_df = consolidated_equities_df.iloc[i : i + batch_size]
    print(f"Processing batch {int(i/batch_size) + 1}/{(total_equities + batch_size - 1) // batch_size} ({len(batch_df)} equities) for historical data...")

    for index, row in batch_df.iterrows():
        ticker = row['Ticker']
        exchange = row['Exchange'] # Get the exchange for the current ticker

        # Call get_historical_metrics_eodhd and append to list
        historical_metrics = get_historical_metrics_eodhd(EODHD_API_KEY, ticker, exchange)
        historical_metrics_list.append(historical_metrics)

    print(f"Finished processing historical data for batch {int(i/batch_size) + 1}. Pausing for 60 seconds to respect API rate limits.")
    time.sleep(60) # Pause for 60 seconds between batches

print(f"Finished fetching historical metrics for {total_equities} equities.")

# Convert historical_metrics_list into a pandas DataFrame
historical_metrics_df = pd.DataFrame(historical_metrics_list)

# Merge historical_metrics_df into the consolidated_equities_df
consolidated_equities_df = consolidated_equities_df.reset_index(drop=True).merge(
    historical_metrics_df.reset_index(drop=True),
    left_index=True, right_index=True
)

print("Historical metrics merged into consolidated_equities_df.")

# Display the first few rows of consolidated_equities_df with historical metrics
print("\nSample of consolidated equities with historical metrics:")
display(consolidated_equities_df.head())

"""### Selectively Fetch Fundamental Metrics for Top Movers

Now that we have historical metrics for all consolidated equities, we can identify the top movers and then fetch fundamental metrics *only* for this smaller, targeted group. This optimizes API usage by avoiding unnecessary fundamental data calls.
"""

# Define periods and number of movers
periods = [30, 90, 360]
num_movers = 25

print(f"Identifying top {num_movers} gainers and losers for periods: {periods} days...")

# Collect all unique tickers from top movers across all periods
unique_movers_tickers = set()

for p in periods:
    top_gainers, top_losers = identify_top_movers(consolidated_equities_df, p, num_movers)
    unique_movers_tickers.update(top_gainers['Ticker'].tolist())
    unique_movers_tickers.update(top_losers['Ticker'].tolist())

print(f"Found {len(unique_movers_tickers)} unique top movers across all specified periods.")

# Filter the consolidated_equities_df to get only the rows for these unique movers
movers_df = consolidated_equities_df[consolidated_equities_df['Ticker'].isin(unique_movers_tickers)].copy()

print("Sample of identified top movers (before fetching fundamentals):")
display(movers_df.head())

print("Fetching fundamental metrics for identified top movers...")

fundamental_metrics_movers_list = []

# Fetch fundamental data for each unique mover
# A small pause for each fundamental call to be safe, as these are more expensive.
for index, row in movers_df.iterrows():
    ticker = row['Ticker']
    exchange = row['Exchange']
    fundamental_metrics = get_fundamental_metrics_from_eodhd(EODHD_API_KEY, ticker, exchange)
    fundamental_metrics_movers_list.append({
        'Ticker': ticker,
        'Exchange': exchange,
        **fundamental_metrics
    })
    time.sleep(0.1) # Small pause between individual fundamental calls

fundamental_metrics_movers_df = pd.DataFrame(fundamental_metrics_movers_list)

# Rename 52WeekHigh and 52WeekLow in fundamental_metrics_movers_df to avoid conflicts
# with historical data (which already has '52WeekHigh' and '52WeekLow' columns)
fundamental_metrics_movers_df = fundamental_metrics_movers_df.rename(columns={
    '52WeekHigh': 'Fundamental_52WeekHigh',
    '52WeekLow': 'Fundamental_52WeekLow'
})

print("Fundamental metrics fetched for movers. Merging back into consolidated DataFrame.")

# Merge these fundamental metrics back into the main consolidated_equities_df
# We'll update existing rows in consolidated_equities_df where tickers match

# Create a temporary DataFrame for merging to avoid modifying the original during the loop
temp_consolidated_df = consolidated_equities_df.set_index(['Ticker', 'Exchange'])
temp_fundamental_df = fundamental_metrics_movers_df.set_index(['Ticker', 'Exchange'])

# Update the fundamental columns only for the movers
updated_movers_data = temp_consolidated_df.combine_first(temp_fundamental_df)

# Reset index and assign back to consolidated_equities_df
consolidated_equities_df = updated_movers_data.reset_index()

print("Consolidated equities DataFrame updated with fundamental metrics for movers.")
print("Sample of consolidated equities with newly merged fundamental metrics:")
display(consolidated_equities_df[consolidated_equities_df['Ticker'].isin(unique_movers_tickers)].head())

"""### Filter Consolidated Equities into US and Foreign Subsets

Now we'll separate the `consolidated_equities_df` into two distinct DataFrames: one for US equities and one for foreign equities. This will facilitate generating separate reports as per your requirements.
"""

# Filter consolidated_equities_df into US and Foreign subsets
us_equities_final_df = consolidated_equities_df[consolidated_equities_df['Source'] == 'US'].copy()
foreign_equities_final_df = consolidated_equities_df[consolidated_equities_df['Source'] == 'Foreign'].copy()

print(f"Total US equities prepared for reporting: {len(us_equities_final_df)}")
print(f"Total Foreign equities prepared for reporting: {len(foreign_equities_final_df)}")

print("\nSample of US Equities Final DataFrame:")
display(us_equities_final_df.head())

print("\nSample of Foreign Equities Final DataFrame:")
display(foreign_equities_final_df.head())

"""## Export Data to Google Sheets

To export data to Google Sheets, we'll use the `gspread` library. First, we need to install it and authenticate your Google account to grant Colab access to your Google Sheets.
"""

# Install gspread library if not already installed
!pip install --quiet gspread

"""### Authenticate gspread

You'll be prompted to authorize access to your Google account. Follow the instructions in the pop-up window.
"""

# import gspread
# from google.colab import auth
# import google.auth # Import google.auth to access default credentials

# # Authenticate with Google Colab
# auth.authenticate_user()

# # Get the authenticated credentials
# credentials, project_id = google.auth.default()

# # Use gspread.authorize() with the authenticated credentials
# gc = gspread.authorize(credentials)
# print("gspread authenticated successfully!")

"""### Non-Interactive gspread Authentication with Service Account

This section demonstrates how to authenticate `gspread` using a service account key, which is essential for automated workflows (e.g., via GCP or GitHub Actions). You need to store your service account JSON key content in Colab secrets under the name `GCS_SERVICE_ACCOUNT_KEY_JSON`.
"""

import gspread
from google.colab import userdata
import json
import os

# Retrieve service account key JSON from Colab secrets
SERVICE_ACCOUNT_KEY_JSON = userdata.get('GCS_SERVICE_ACCOUNT_KEY_JSON')

if not SERVICE_ACCOUNT_KEY_JSON:
    print("GCS_SERVICE_ACCOUNT_KEY_JSON not found in Colab secrets. Please add it for non-interactive authentication.")
else:
    try:
        # Write the JSON string to a temporary file
        # In a production environment, you would typically load this directly from a secure source
        # without writing to disk.
        temp_key_file = 'service_account_key.json'
        with open(temp_key_file, 'w') as f:
            f.write(SERVICE_ACCOUNT_KEY_JSON)

        # Authenticate gspread using the service account key file
        gc_service_account = gspread.service_account(filename=temp_key_file)
        print("gspread authenticated successfully using service account!")

        # Clean up the temporary file (optional, but good practice)
        os.remove(temp_key_file)

        # You can now use gc_service_account for non-interactive operations
        # For example, to open a spreadsheet:
        # spreadsheet = gc_service_account.open("My Stock Reports")
        # print(f"Opened spreadsheet: {spreadsheet.title}")

    except json.JSONDecodeError:
        print("Error: GCS_SERVICE_ACCOUNT_KEY_JSON is not a valid JSON string.")
    except Exception as e:
        print(f"Error during service account authentication: {e}")

# Note: The original 'gc' client from interactive authentication might still be active
# if the previous cell was run. For automation, you would only use the service account client.

"""### `export_to_google_sheets` Function

This function will take a DataFrame, a spreadsheet name, and a worksheet name, then write the DataFrame's contents to the specified sheet. It will create the spreadsheet or worksheet if they don't already exist.
"""

def export_to_google_sheets(df, spreadsheet_name, worksheet_name, start_cell='A1', clear_contents=True, include_header=True, max_expected_rows=2000, max_expected_cols=50):
    """
    Exports a pandas DataFrame to a specified Google Sheet worksheet.

    Args:
        df (pd.DataFrame): The DataFrame to export.
        spreadsheet_name (str): The name of the Google Spreadsheet.
        worksheet_name (str): The name of the worksheet within the spreadsheet.
        start_cell (str): The top-left cell where the DataFrame should start (e.g., 'A1').
        clear_contents (bool): If True, clears the worksheet contents before writing.
                                Set to False if appending to a sheet or writing to specific parts.
        include_header (bool): If True, writes the DataFrame header. Set to False if only writing data.
        max_expected_rows (int): Max rows to pre-allocate if creating a new worksheet.
        max_expected_cols (int): Max cols to pre-allocate if creating a new worksheet.
    """
    print(f"Attempting to export data to '{spreadsheet_name}' -> '{worksheet_name}' starting at {start_cell}...")
    try:
        # Use gc_service_account instead of gc
        spreadsheet = gc_service_account.open(spreadsheet_name)
    except gspread.exceptions.SpreadsheetNotFound:
        print(f"Spreadsheet '{spreadsheet_name}' not found. Creating a new one...")
        # Use gc_service_account instead of gc
        spreadsheet = gc_service_account.create(spreadsheet_name)
        # Removed: spreadsheet.share(gc.auth.service_account_email, perm_type='user', role='writer')
        print(f"Spreadsheet '{spreadsheet_name}' created.")

    try:
        worksheet = spreadsheet.worksheet(worksheet_name)
        if clear_contents:
            worksheet.clear()
            print(f"Worksheet '{worksheet_name}' found and cleared.")
    except gspread.exceptions.WorksheetNotFound:
        print(f"Worksheet '{worksheet_name}' not found. Creating a new one with {max_expected_rows} rows and {max_expected_cols} columns...")
        worksheet = spreadsheet.add_worksheet(title=worksheet_name, rows=max_expected_rows, cols=max_expected_cols)

    # Prepare data to write
    data_to_write = []
    if include_header:
        data_to_write.append(df.columns.values.tolist())
    data_to_write.extend(df.values.tolist())

    if data_to_write:
        worksheet.update(data_to_write, range_name=start_cell)
        print(f"Data successfully exported to Google Sheet: '{spreadsheet_name}' -> '{worksheet_name}' starting at {start_cell}.")
    else:
        print(f"No data to write to Google Sheet: '{spreadsheet_name}' -> '{worksheet_name}' at {start_cell}.")

from datetime import datetime # Import datetime for report dates

def export_all_reports_to_sheets(consolidated_df, spreadsheet_name, num_movers=25):
    """
    Orchestrates the export of all defined reports (Daily, Weekly; US, Foreign)
    to a Google Sheet. It places US and Foreign equities in the same sheet,
    separated by a marker, and Gainers and Losers side-by-side.

    Args:
        consolidated_df (pd.DataFrame): The DataFrame containing all consolidated equities data.
        spreadsheet_name (str): The name of the Google Spreadsheet to export to.
        num_movers (int): The number of top gainers/losers to identify for *each* category (US/Foreign).
    """
    print(f"\n--- Starting export of all reports to '{spreadsheet_name}' ---")

    # Get today's date for report names
    report_date = datetime.now().strftime('%Y-%m-%d')
    current_day_of_week = datetime.now().weekday() # Monday is 0, Friday is 4

    # Display columns for the final reports - REMOVED 'Source' column
    display_cols = [
        'Ticker', 'Name', 'MarketCap', 'Exchange',
        'Change_30D', 'Change_90D', 'Change_360D',
        'LatestClosePrice', 'Fundamental_52WeekHigh', 'Fundamental_52WeekLow',
        'PriceToSales', 'PriceToEarnings', 'PEGRatio', 'DividendYield'
    ]
    num_display_cols = len(display_cols)

    # Periods for reporting
    report_periods = {
        'Daily Report': [30],
        'Weekly Report': [90, 360]
    }

    # Separator rows for clarity within the sheet (defined once)
    us_foreign_separator_row_data = {col: '' for col in display_cols}
    us_foreign_separator_row_data['Ticker'] = '--- FOREIGN EQUITIES START ---'
    us_foreign_separator_df = pd.DataFrame([us_foreign_separator_row_data])

    # Empty rows for visual spacing (defined once)
    empty_rows_df_template = pd.DataFrame([[''] * num_display_cols] * 3, columns=display_cols) # 3 empty rows

    # Estimate max rows/cols needed for new worksheet creation (being generous)
    # Max rows for one side (e.g., Gainers) will be num_movers (US) + separators + num_movers (Foreign)
    total_max_expected_rows = (num_movers * 2) + (len(empty_rows_df_template) * 2) + len(us_foreign_separator_df) + 5 # 25 US + 25 Foreign + separators + buffer
    total_max_expected_cols = num_display_cols * 2 + 5 # Gainers + Losers + buffer

    # Open the spreadsheet or create if not exists
    try:
        spreadsheet = gc_service_account.open(spreadsheet_name)
    except gspread.exceptions.SpreadsheetNotFound:
        print(f"Spreadsheet '{spreadsheet_name}' not found. Creating a new one...")
        spreadsheet = gc_service_account.create(spreadsheet_name)
        print(f"Spreadsheet '{spreadsheet_name}' created.")

    # Get all existing worksheets to manage visibility
    existing_worksheets = spreadsheet.worksheets()
    current_date_obj = datetime.strptime(report_date, '%Y-%m-%d').date()

    for ws in existing_worksheets:
        try:
            # Attempt to parse date from worksheet name
            ws_name = ws.title
            # Example patterns: 'YYYY-MM-DD (30D Movers)', 'Week of YYYY-MM-DD (90D Movers)'
            if ' (' in ws_name:
                date_str_part = ws_name.split(' (')[0]
                if 'Week of ' in date_str_part:
                    date_str = date_str_part.replace('Week of ', '')
                else:
                    date_str = date_str_part

                ws_date_obj = datetime.strptime(date_str, '%Y-%m-%d').date()

                if ws_date_obj < current_date_obj:
                    print(f"Hiding old worksheet: {ws.title}")
                    ws.hide()
                else:
                    print(f"Keeping current worksheet visible: {ws.title}")
            else:
                # If date pattern not found, assume it's a fixed or unknown tab, keep visible
                print(f"Skipping date parsing for worksheet: {ws.title} (unknown naming convention).")
        except ValueError:
            # Date parsing failed, likely not a dated report tab, keep visible
            print(f"Skipping date parsing for worksheet: {ws.title} (date not found or format mismatch).")
        except Exception as e:
            print(f"Error processing worksheet {ws.title}: {e}")

    # Prepare US and Foreign DataFrames once for efficiency
    us_equities_data = consolidated_df[consolidated_df['Source'] == 'US'].copy()
    foreign_equities_data = consolidated_df[consolidated_df['Source'] == 'Foreign'].copy()

    for report_type, periods_list in report_periods.items():
        for p in periods_list:
            # Conditional execution based on day of week
            if p in [90, 360] and current_day_of_week != 4: # Monday=0, Friday=4
                print(f"Skipping {p}D report: Not Friday (current day: {current_day_of_week}).")
                continue # Skip this period and move to the next

            if report_type == 'Daily Report':
                worksheet_name = f"{report_date} ({p}D Movers)"
            elif report_type == 'Weekly Report':
                # For weekly reports, we might want to name it by the week start date, but sticking to current date for now.
                worksheet_name = f"Week of {report_date} ({p}D Movers)"
            else:
                worksheet_name = f"{report_type} ({p}D Movers)" # Fallback, though not expected

            print(f"\nGenerating {worksheet_name} report...")

            # --- Identify US and Foreign Gainers/Losers separately ---
            us_gainers, us_losers = identify_top_movers(us_equities_data, p, num_movers)
            foreign_gainers, foreign_losers = identify_top_movers(foreign_equities_data, p, num_movers)

            # --- Construct Gainers DataFrame (US on top, Foreign below) ---
            gainers_df_to_write = pd.DataFrame(columns=display_cols)
            if not us_gainers.empty:
                gainers_df_to_write = pd.concat([gainers_df_to_write, format_financial_df(us_gainers[display_cols])], ignore_index=True)

            if not us_gainers.empty and not foreign_gainers.empty:
                gainers_df_to_write = pd.concat([gainers_df_to_write, empty_rows_df_template, us_foreign_separator_df, empty_rows_df_template], ignore_index=True)

            if not foreign_gainers.empty:
                gainers_df_to_write = pd.concat([gainers_df_to_write, format_financial_df(foreign_gainers[display_cols])], ignore_index=True)

            # --- Construct Losers DataFrame (US on top, Foreign below) ---
            losers_df_to_write = pd.DataFrame(columns=display_cols)
            if not us_losers.empty:
                losers_df_to_write = pd.concat([losers_df_to_write, format_financial_df(us_losers[display_cols])], ignore_index=True)

            if not us_losers.empty and not foreign_losers.empty:
                losers_df_to_write = pd.concat([losers_df_to_write, empty_rows_df_template, us_foreign_separator_df, empty_rows_df_template], ignore_index=True)

            if not foreign_losers.empty:
                losers_df_to_write = pd.concat([losers_df_to_write, format_financial_df(foreign_losers[display_cols])], ignore_index=True)

            # Determine the starting column for Losers
            # Example: if num_display_cols is 15 (A-O), then Losers start at column R (P, Q empty, R)
            losers_start_col_letter = chr(ord('A') + num_display_cols + 2) # +2 for some empty columns between gainers and losers
            losers_start_cell = f"{losers_start_col_letter}1"

            # Export to Google Sheet
            # First, clear the sheet and export Gainers to the left (A1)
            export_to_google_sheets(
                gainers_df_to_write, spreadsheet_name, worksheet_name,
                start_cell='A1', clear_contents=True, include_header=True,
                max_expected_rows=total_max_expected_rows, max_expected_cols=total_max_expected_cols
            )

            # Then, export Losers to the same sheet, starting at the calculated column
            # No need to clear contents again, but include header.
            if not losers_df_to_write.empty:
                export_to_google_sheets(
                    losers_df_to_write, spreadsheet_name, worksheet_name,
                    start_cell=losers_start_cell, clear_contents=False, include_header=True,
                    max_expected_rows=total_max_expected_rows, max_expected_cols=total_max_expected_cols
                )
            else:
                print(f"No losers data to export for {worksheet_name}.")

    print("--- All reports exported successfully! ---")

# Call the master export function with your consolidated data
# Replace 'My Stock Reports' with your desired Google Sheet name
spreadsheet_name = 'Stock Market Movers Report'

if 'consolidated_equities_df' in locals():
    export_all_reports_to_sheets(consolidated_equities_df, spreadsheet_name, num_movers=25)
else:
    print("Error: consolidated_equities_df is not defined. Please ensure previous steps ran successfully.")

print("\n--- Null value counts for Change_30D, Change_90D, and Change_360D ---")
print(consolidated_equities_df[['Change_30D', 'Change_90D', 'Change_360D']].isnull().sum())

print("\nTickers with missing historical data (Change_30D is NaN):")
missing_historical_data_tickers = consolidated_equities_df[consolidated_equities_df['Change_30D'].isnull()][['Ticker', 'Exchange']]
print(missing_historical_data_tickers)